### ISSUE TITLE
Colab collapses

### ISSUE THREAD

**Issue by shainaraza** [bernaljg/covid19-classification#11]
I tried to run litcovid_dataset_from_xml.py but my google colab pro collapses due to data set size (After unzipping ofcourse).
Any help

**Comment by bernaljg** [comment]
If you're trying to run it with new data from LitCovid it's probably a lot larger now. I might be able to help if you post the error message. However, if its only an issue caused by not having enough memory in your google colab pro you might need to increase your memory or find a different way to load the data in.

**Comment by shainaraza** [comment]
thanks for quick reply.
is there any quick way to load it? i mean some truncation during bioc.load?
any advise?

**Comment by shainaraza** [comment]
yes i want to restrict, i think your file litcovid.sh is for that?

**Comment by shainaraza** [comment]
this was my error
<html>
<body>


tcmalloc: large alloc 80000000000 bytes == 0x561a90d84000 @ 0x7f460a1ac001 0x561a8ca3bc60 0x561a8ca18dd0 0x561a8ca79a2e 0x561a8ca779ee 0x561a8ca776f3 0x561a8ca75b60 0x561a8ca09349 0x561a8ca09240 0x561a8ca7c973 0x561a8ca779ee 0x561a8ca0abda 0x561a8ca78c0d 0x561a8ca779ee 0x561a8ca0abda 0x561a8ca79737 0x561a8ca77ced 0x561a8ca0b48c 0x561a8ca0b698 0x561a8ca79fe4 0x561a8ca77ced 0x561a8ca0abda 0x561a8ca79737 0x561a8ca779ee 0x561a8ca0abda 0x561a8ca78c0d 0x561a8ca0aafa 0x561a8ca78915 0x561a8ca0aafa 0x561a8ca78c0d 0x561a8ca77ced
--


<br class="Apple-interchange-newline">
</body>
</html>

**Comment by bernaljg** [comment]
Take a look at the section on "Incrementally decoding the BioC XML file" in the bioc documentation here https://pypi.org/project/bioc/. It seems to be exactly what you need.

**Comment by shainaraza** [comment]
I tried this too, issue is with load() function.

**Comment by shainaraza** [comment]
I split xml into blocks
lets see if it work,
thanks

**Comment by shainaraza** [comment]
thanks @bernaljg it worked after i spplit XML into couple of file.s
