### ISSUE TITLE
litcovid_source*.tsv missing

### ISSUE THREAD

**Issue by shainaraza** [bernaljg/covid19-classification#13]
where can i find these files

files = glob.glob(source_file_path+"/litcovid_source*.tsv")

**Comment by bernaljg** [comment]
it should automatically download those files in the script "load_litcovid.sh" before running litcovid_dataset_from_xml.py.

**Comment by shainaraza** [comment]
oh ok, I downloaded only actual xml file, leaving other curl commands, i will check, thanks

**Comment by shainaraza** [comment]
thanks you @bernaljg , all issues are resolved, how may I thank you for this.
